version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update Debian package repositories
          command: |
            sudo sed -i '/stretch-updates/d' /etc/apt/sources.list
            sudo sed -i '/stretch/d' /etc/apt/sources.list
            sudo apt-get update
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get install -y docker-ce
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app .
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag my-app $DOCKERHUB_USERNAME/my-app
            docker push $DOCKERHUB_USERNAME/my-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main

